### ISSUE TITLE
Add WhatsApp redirect button

### ISSUE THREAD

**Issue by ArielMAJ** [tauanesales/GES_website#20]
How to: https://faq.whatsapp.com/5913398998672934
https://about.meta.com/br/brand/resources/whatsapp/whatsapp-brand

- [X] Add WA image to project;
- [X] Create personalized WA link;
- [x] Make WA image float, always on top of everything, in the bottom right corner;
- [x] Wrap image with Anchor tag using personalized WA link;

**Comment by tauanesales** [comment]
PRs #21, #23 and #25 resolve this issue.
